In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

print("CashFlowIQ - Data Cleaning & Transformation")
print("Python environment is working!")

CashFlowIQ - Data Cleaning & Transformation
Python environment is working!

In [7]:
# Project paths

project_path = Path.cwd().parent
data_path = project_path / "Data"
clean_path = project_path / "Clean_Data"

# Create Clean_Data folder if it does not already exist
clean_path.mkdir(exist_ok=True)

print("Project:", project_path)
print("Raw Data:", data_path)
print("Clean Data:", clean_path)
print("Clean_Data folder exists:", clean_path.exists())

Project: d:\DATA ANALYST PROJECTS\Analytics_Projects\CashFlowIQ
Raw Data: d:\DATA ANALYST PROJECTS\Analytics_Projects\CashFlowIQ\Data
Clean Data: d:\DATA ANALYST PROJECTS\Analytics_Projects\CashFlowIQ\Clean_Data
Clean_Data folder exists: True

In [8]:
# Load raw tables

customers = pd.read_csv(data_path / "customers.csv")
vendors = pd.read_csv(data_path / "vendors.csv")
products = pd.read_csv(data_path / "products.csv")

sales = pd.read_csv(data_path / "sales_invoices.csv")
vendor_invoices = pd.read_csv(data_path / "vendor_invoices.csv")

operating_expenses = pd.read_csv(
    data_path / "operating_expenses.csv"
)

payroll = pd.read_csv(data_path / "payroll.csv")

loans = pd.read_csv(data_path / "loans.csv")
loan_payments = pd.read_csv(data_path / "loan_payments.csv")

bank_transactions = pd.read_csv(
    data_path / "bank_transactions.csv"
)

inventory = pd.read_csv(
    data_path / "inventory_snapshots.csv"
)

print("All 11 raw tables loaded successfully.")

All 11 raw tables loaded successfully.

In [5]:
# Convert date columns to proper datetime format

date_columns = {
    "sales": [
        "invoice_date",
        "due_date",
        "payment_date"
    ],
    
    "vendor_invoices": [
        "invoice_date",
        "due_date",
        "payment_date"
    ],
    
    "operating_expenses": [
        "expense_date"
    ],
    
    "payroll": [
        "pay_date"
    ],
    
    "loans": [
        "start_date"
    ],
    
    "loan_payments": [
        "payment_date"
    ],
    
    "bank_transactions": [
        "transaction_date"
    ],
    
    "inventory": [
        "snapshot_date"
    ]
}

dataframes = {
    "sales": sales,
    "vendor_invoices": vendor_invoices,
    "operating_expenses": operating_expenses,
    "payroll": payroll,
    "loans": loans,
    "loan_payments": loan_payments,
    "bank_transactions": bank_transactions,
    "inventory": inventory
}

for table_name, columns in date_columns.items():
    
    df = dataframes[table_name]
    
    for column in columns:
        df[column] = pd.to_datetime(
            df[column],
            errors="coerce"
        )

print("Date conversion completed.")

Date conversion completed.

In [6]:
# ============================================================
# SALES / RECEIVABLES TRANSFORMATION
# ============================================================

# Payment status
sales["payment_status"] = np.where(
    sales["payment_date"].notna(),
    "Paid",
    "Outstanding"
)

# Days taken to pay
sales["days_to_pay"] = (
    sales["payment_date"] - sales["invoice_date"]
).dt.days

# Days late
sales["days_late"] = (
    sales["payment_date"] - sales["due_date"]
).dt.days

# For unpaid invoices, calculate days overdue as of dataset end
as_of_date = pd.Timestamp("2026-08-31")

unpaid_mask = sales["payment_date"].isna()

sales.loc[unpaid_mask, "days_late"] = (
    as_of_date - sales.loc[unpaid_mask, "due_date"]
).dt.days

# Negative lateness means invoice is not overdue yet
sales["days_late"] = sales["days_late"].clip(lower=0)

# Invoice month
sales["invoice_month"] = (
    sales["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

print(
    sales[
        [
            "invoice_id",
            "invoice_date",
            "due_date",
            "payment_date",
            "payment_status",
            "days_to_pay",
            "days_late",
            "invoice_month"
        ]
    ].head(10)
)

  invoice_id invoice_date   due_date payment_date payment_status  days_to_pay  \
0   SI100001   2025-04-05 2025-04-20   2025-04-28           Paid         23.0
1   SI100002   2026-01-09 2026-01-24   2026-02-06           Paid         28.0
2   SI100003   2026-06-04 2026-07-04   2026-07-04           Paid         30.0
3   SI100004   2025-12-26 2026-01-25   2026-02-09           Paid         45.0
4   SI100005   2025-10-08 2025-11-22   2025-12-03           Paid         56.0
5   SI100006   2025-07-14 2025-08-28   2025-09-21           Paid         69.0
6   SI100007   2025-07-14 2025-08-28   2025-09-03           Paid         51.0
7   SI100008   2025-04-03 2025-05-18   2025-05-18           Paid         45.0
8   SI100009   2025-03-02 2025-04-01   2025-04-06           Paid         35.0
9   SI100010   2025-02-20 2025-03-07   2025-03-09           Paid         17.0

   days_late invoice_month
0        8.0       2025-04
1       13.0       2026-01
2        0.0       2026-06
3       15.0       2025-12
4       11.0       2025-10
5       24.0       2025-07
6        6.0       2025-07
7        0.0       2025-04
8        5.0       2025-03
9        2.0       2025-02

In [7]:
# ============================================================
# RECEIVABLES AGEING
# ============================================================

def ageing_bucket(days_late, payment_status):
    
    if payment_status == "Paid":
        return "Paid"
    
    if days_late <= 0:
        return "Current"
    
    elif days_late <= 30:
        return "1-30 Days"
    
    elif days_late <= 60:
        return "31-60 Days"
    
    elif days_late <= 90:
        return "61-90 Days"
    
    else:
        return "90+ Days"


sales["ageing_bucket"] = sales.apply(
    lambda row: ageing_bucket(
        row["days_late"],
        row["payment_status"]
    ),
    axis=1
)

print(
    sales[
        [
            "invoice_id",
            "payment_status",
            "days_late",
            "ageing_bucket"
        ]
    ].head(15)
)

   invoice_id payment_status  days_late ageing_bucket
0    SI100001           Paid        8.0          Paid
1    SI100002           Paid       13.0          Paid
2    SI100003           Paid        0.0          Paid
3    SI100004           Paid       15.0          Paid
4    SI100005           Paid       11.0          Paid
5    SI100006           Paid       24.0          Paid
6    SI100007           Paid        6.0          Paid
7    SI100008           Paid        0.0          Paid
8    SI100009           Paid        5.0          Paid
9    SI100010           Paid        2.0          Paid
10   SI100011           Paid        3.0          Paid
11   SI100012           Paid        4.0          Paid
12   SI100013           Paid        0.0          Paid
13   SI100014           Paid        7.0          Paid
14   SI100015           Paid        0.0          Paid

In [8]:
# ============================================================
# VENDOR PAYABLES TRANSFORMATION
# ============================================================

vendor_invoices["payment_status"] = np.where(
    vendor_invoices["payment_date"].notna(),
    "Paid",
    "Outstanding"
)

# Days taken to pay vendor
vendor_invoices["days_to_pay"] = (
    vendor_invoices["payment_date"]
    - vendor_invoices["invoice_date"]
).dt.days

# Days late
vendor_invoices["days_late"] = (
    vendor_invoices["payment_date"]
    - vendor_invoices["due_date"]
).dt.days

# Calculate overdue days for unpaid vendor invoices
unpaid_vendor_mask = (
    vendor_invoices["payment_date"].isna()
)

vendor_invoices.loc[
    unpaid_vendor_mask,
    "days_late"
] = (
    as_of_date
    - vendor_invoices.loc[
        unpaid_vendor_mask,
        "due_date"
    ]
).dt.days

# Prevent negative overdue days
vendor_invoices["days_late"] = (
    vendor_invoices["days_late"]
    .clip(lower=0)
)

# Invoice month
vendor_invoices["invoice_month"] = (
    vendor_invoices["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

print(
    vendor_invoices[
        [
            "vendor_invoice_id",
            "vendor_id",
            "invoice_date",
            "due_date",
            "payment_date",
            "payment_status",
            "days_to_pay",
            "days_late",
            "invoice_month"
        ]
    ].head(10)
)

  vendor_invoice_id vendor_id invoice_date   due_date payment_date  \
0          VI200001     V2007   2026-01-24 2026-02-23   2026-02-23
1          VI200002     V2005   2026-03-11 2026-04-25   2026-05-08
2          VI200003     V2031   2026-05-11 2026-06-10   2026-06-11
3          VI200004     V2019   2025-07-20 2025-08-19   2025-08-25
4          VI200005     V2004   2026-06-18 2026-07-18   2026-07-18
5          VI200006     V2022   2025-10-24 2025-12-23   2025-12-30
6          VI200007     V2003   2026-05-09 2026-06-08   2026-06-08
7          VI200008     V2023   2025-11-27 2026-01-11   2026-01-31
8          VI200009     V2004   2025-09-18 2025-10-18   2025-10-18
9          VI200010     V2024   2025-02-24 2025-03-26   2025-04-07

  payment_status  days_to_pay  days_late invoice_month
0           Paid         30.0        0.0       2026-01
1           Paid         58.0       13.0       2026-03
2           Paid         31.0        1.0       2026-05
3           Paid         36.0        6.0       2025-07
4           Paid         30.0        0.0       2026-06
5           Paid         67.0        7.0       2025-10
6           Paid         30.0        0.0       2026-05
7           Paid         65.0       20.0       2025-11
8           Paid         30.0        0.0       2025-09
9           Paid         42.0       12.0       2025-02

In [9]:
# ============================================================
# PAYABLES AGEING BUCKET
# ============================================================

vendor_invoices["ageing_bucket"] = vendor_invoices.apply(
    lambda row: ageing_bucket(
        row["days_late"],
        row["payment_status"]
    ),
    axis=1
)

print(
    vendor_invoices[
        [
            "vendor_invoice_id",
            "payment_status",
            "days_late",
            "ageing_bucket"
        ]
    ].head(15)
)

   vendor_invoice_id payment_status  days_late ageing_bucket
0           VI200001           Paid        0.0          Paid
1           VI200002           Paid       13.0          Paid
2           VI200003           Paid        1.0          Paid
3           VI200004           Paid        6.0          Paid
4           VI200005           Paid        0.0          Paid
5           VI200006           Paid        7.0          Paid
6           VI200007           Paid        0.0          Paid
7           VI200008           Paid       20.0          Paid
8           VI200009           Paid        0.0          Paid
9           VI200010           Paid       12.0          Paid
10          VI200011           Paid        0.0          Paid
11          VI200012           Paid        2.0          Paid
12          VI200013           Paid        0.0          Paid
13          VI200014           Paid        0.0          Paid
14          VI200015           Paid        8.0          Paid

In [10]:
# ============================================================
# OPERATING EXPENSE TRANSFORMATION
# ============================================================

operating_expenses["expense_month"] = (
    operating_expenses["expense_date"]
    .dt.to_period("M")
    .astype(str)
)

# Ensure amount is numeric
operating_expenses["expense_amount"] = pd.to_numeric(
    operating_expenses["expense_amount"],
    errors="coerce"
)

print(
    operating_expenses.head(10)
)

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
operating_expenses.columns.tolist()

['expense_id', 'expense_date', 'expense_category', 'amount', 'expense_month']

In [ ]:
operating_expenses.head()

  expense_id expense_date expense_category     amount expense_month
0   EX400001   2025-01-01          Payroll  916245.95       2025-01
1   EX400002   2025-01-01             Rent  185869.91       2025-01
2   EX400003   2025-01-01        Utilities   63746.62       2025-01
3   EX400004   2025-01-01        Marketing  165352.65       2025-01
4   EX400005   2025-01-01         Software   88814.48       2025-01

In [ ]:
# ============================================================
# OPERATING EXPENSE TRANSFORMATION - CORRECTED
# ============================================================

# Ensure expense date is datetime
operating_expenses["expense_date"] = pd.to_datetime(
    operating_expenses["expense_date"],
    errors="coerce"
)

# Ensure amount is numeric
operating_expenses["amount"] = pd.to_numeric(
    operating_expenses["amount"],
    errors="coerce"
)

# Ensure expense month is correctly formatted
operating_expenses["expense_month"] = (
    operating_expenses["expense_date"]
    .dt.to_period("M")
    .astype(str)
)

print(
    operating_expenses[
        [
            "expense_id",
            "expense_date",
            "expense_category",
            "amount",
            "expense_month"
        ]
    ].head(10)
)

  expense_id expense_date       expense_category     amount expense_month
0   EX400001   2025-01-01                Payroll  916245.95       2025-01
1   EX400002   2025-01-01                   Rent  185869.91       2025-01
2   EX400003   2025-01-01              Utilities   63746.62       2025-01
3   EX400004   2025-01-01              Marketing  165352.65       2025-01
4   EX400005   2025-01-01               Software   88814.48       2025-01
5   EX400006   2025-01-01                 Travel   65460.04       2025-01
6   EX400007   2025-01-01              Insurance   49942.85       2025-01
7   EX400008   2025-01-01  Professional Services  103057.90       2025-01
8   EX400009   2025-02-01                Payroll  979212.27       2025-02
9   EX400010   2025-02-01                   Rent  196297.68       2025-02

In [ ]:
# ============================================================
# MONTHLY EXPENSE SUMMARY
# ============================================================

monthly_expenses = (
    operating_expenses
    .groupby(
        "expense_month",
        as_index=False
    )
    .agg(
        total_expenses=("amount", "sum")
    )
)

print(monthly_expenses.head(10))

  expense_month  total_expenses
0       2025-01      1638490.40
1       2025-02      1684994.10
2       2025-03      1555568.42
3       2025-04      1652426.12
4       2025-05      1566320.02
5       2025-06      1660369.58
6       2025-07      1687080.77
7       2025-08      1540399.59
8       2025-09      1630926.98
9       2025-10      1702014.74

In [ ]:
# ============================================================
# PAYROLL TRANSFORMATION
# ============================================================

payroll["pay_date"] = pd.to_datetime(
    payroll["pay_date"],
    errors="coerce"
)

payroll["pay_month"] = (
    payroll["pay_date"]
    .dt.to_period("M")
    .astype(str)
)

payroll["employee_cost"] = pd.to_numeric(
    payroll["gross_payroll"],
    errors="coerce"
)

print(
    payroll[
        [
            "pay_date",
            "pay_month",
            "gross_payroll",
            "net_payroll",
            "employee_cost"
        ]
    ].head(10)
)

    pay_date pay_month  gross_payroll  net_payroll  employee_cost
0 2025-01-28   2025-01      851940.78    744888.64      851940.78
1 2025-02-28   2025-02      857492.39    759701.77      857492.39
2 2025-03-28   2025-03      857181.35    771338.76      857181.35
3 2025-04-28   2025-04      861824.28    761983.07      861824.28
4 2025-05-28   2025-05      911705.53    791191.14      911705.53
5 2025-06-28   2025-06      886464.65    764346.70      886464.65
6 2025-07-28   2025-07      918016.37    816113.22      918016.37
7 2025-08-28   2025-08      907557.33    783343.75      907557.33
8 2025-09-28   2025-09      951876.91    823672.47      951876.91
9 2025-10-28   2025-10      962663.31    850735.45      962663.31

In [ ]:
monthly_payroll = (
    payroll
    .groupby(
        "pay_month",
        as_index=False
    )
    .agg(
        total_payroll=("employee_cost", "sum")
    )
)

print(monthly_payroll.head(10))

  pay_month  total_payroll
0   2025-01      851940.78
1   2025-02      857492.39
2   2025-03      857181.35
3   2025-04      861824.28
4   2025-05      911705.53
5   2025-06      886464.65
6   2025-07      918016.37
7   2025-08      907557.33
8   2025-09      951876.91
9   2025-10      962663.31

In [ ]:
# ============================================================
# BANK TRANSACTION TRANSFORMATION
# ============================================================

bank_transactions["transaction_date"] = pd.to_datetime(
    bank_transactions["transaction_date"],
    errors="coerce"
)

bank_transactions["transaction_month"] = (
    bank_transactions["transaction_date"]
    .dt.to_period("M")
    .astype(str)
)

print(
    bank_transactions[
        [
            "transaction_date",
            "amount",
            "transaction_month"
        ]
    ].head(10)
)

  transaction_date       amount transaction_month
0       2025-01-01  12000000.00           2025-01
1       2025-01-18      2865.19           2025-01
2       2025-01-22     -7692.25           2025-01
3       2025-01-22     -4384.09           2025-01
4       2025-01-23      3628.27           2025-01
5       2025-01-23      2650.48           2025-01
6       2025-01-28   -103057.90           2025-01
7       2025-01-28    -49942.85           2025-01
8       2025-01-28    -65460.04           2025-01
9       2025-01-28    -88814.48           2025-01

In [ ]:
# ============================================================
# CASH FLOW DIRECTION
# ============================================================

bank_transactions["amount"] = pd.to_numeric(
    bank_transactions["amount"],
    errors="coerce"
)

bank_transactions["cash_flow_direction"] = np.where(
    bank_transactions["amount"] >= 0,
    "Inflow",
    "Outflow"
)

bank_transactions["absolute_amount"] = (
    bank_transactions["amount"].abs()
)

print(
    bank_transactions[
        [
            "transaction_date",
            "amount",
            "cash_flow_direction",
            "absolute_amount",
            "transaction_month"
        ]
    ].head(15)
)

   transaction_date       amount cash_flow_direction  absolute_amount  \
0        2025-01-01  12000000.00              Inflow      12000000.00
1        2025-01-18      2865.19              Inflow          2865.19
2        2025-01-22     -7692.25             Outflow          7692.25
3        2025-01-22     -4384.09             Outflow          4384.09
4        2025-01-23      3628.27              Inflow          3628.27
5        2025-01-23      2650.48              Inflow          2650.48
6        2025-01-28   -103057.90             Outflow        103057.90
7        2025-01-28    -49942.85             Outflow         49942.85
8        2025-01-28    -65460.04             Outflow         65460.04
9        2025-01-28    -88814.48             Outflow         88814.48
10       2025-01-28   -165352.65             Outflow        165352.65
11       2025-01-28   -916245.95             Outflow        916245.95
12       2025-01-28   -185869.91             Outflow        185869.91
13       2025-01-28      1785.58              Inflow          1785.58
14       2025-01-28      7520.80              Inflow          7520.80

   transaction_month
0            2025-01
1            2025-01
2            2025-01
3            2025-01
4            2025-01
5            2025-01
6            2025-01
7            2025-01
8            2025-01
9            2025-01
10           2025-01
11           2025-01
12           2025-01
13           2025-01
14           2025-01

In [ ]:
# ============================================================
# MONTHLY CASH FLOW SUMMARY
# ============================================================

cashflow_summary = (
    bank_transactions
    .assign(
        inflow=np.where(
            bank_transactions["amount"] > 0,
            bank_transactions["amount"],
            0
        ),
        outflow=np.where(
            bank_transactions["amount"] < 0,
            bank_transactions["amount"].abs(),
            0
        )
    )
    .groupby(
        "transaction_month",
        as_index=False
    )
    .agg(
        total_inflow=("inflow", "sum"),
        total_outflow=("outflow", "sum")
    )
)

cashflow_summary["net_cash_flow"] = (
    cashflow_summary["total_inflow"]
    - cashflow_summary["total_outflow"]
)

print(cashflow_summary)

   transaction_month  total_inflow  total_outflow  net_cash_flow
0            2025-01   12058638.04     2396314.85     9662323.19
1            2025-02    1286505.14     2887502.30    -1600997.16
2            2025-03    2103810.78     2835197.13     -731386.35
3            2025-04    2262549.75     2922434.53     -659884.78
4            2025-05    2399035.25     3005112.91     -606077.66
5            2025-06    2118683.62     3051559.36     -932875.74
6            2025-07    2348714.26     3252295.11     -903580.85
7            2025-08    2161657.23     3028738.63     -867081.40
8            2025-09    2711038.05     3176969.76     -465931.71
9            2025-10    2161971.26     3380333.58    -1218362.32
10           2025-11    2495562.56     3208304.26     -712741.70
11           2025-12    2356177.29     3340383.94     -984206.65
12           2026-01    2187896.95     3341948.17    -1154051.22
13           2026-02    2062908.01     3305649.46    -1242741.45
14           2026-03    2379861.87     3326936.50     -947074.63
15           2026-04    2060250.84     3325784.95    -1265534.11
16           2026-05    2018032.06     3378286.68    -1360254.62
17           2026-06    2131425.28     3502393.03    -1370967.75
18           2026-07    2309080.56     3364676.38    -1055595.82
19           2026-08    1164309.58     3197593.75    -2033284.17
20           2026-09      70008.98       22756.60       47252.38

In [ ]:
# ============================================================
# INVENTORY TRANSFORMATION
# ============================================================

inventory["snapshot_date"] = pd.to_datetime(
    inventory["snapshot_date"],
    errors="coerce"
)

inventory["snapshot_month"] = (
    inventory["snapshot_date"]
    .dt.to_period("M")
    .astype(str)
)

inventory["inventory_value"] = pd.to_numeric(
    inventory["inventory_value"],
    errors="coerce"
)

inventory["units_on_hand"] = pd.to_numeric(
    inventory["units_on_hand"],
    errors="coerce"
)

print(
    inventory[
        [
            "snapshot_date",
            "snapshot_month",
            "product_id",
            "units_on_hand",
            "inventory_value"
        ]
    ].head(10)
)

  snapshot_date snapshot_month product_id  units_on_hand  inventory_value
0    2025-01-01        2025-01      P3001             71         80651.03
1    2025-01-01        2025-01      P3002             84        169772.40
2    2025-01-01        2025-01      P3003             86        210400.72
3    2025-01-01        2025-01      P3004             59         84106.27
4    2025-01-01        2025-01      P3005             84         72315.60
5    2025-01-01        2025-01      P3006             66         12211.98
6    2025-01-01        2025-01      P3007             52        120517.28
7    2025-01-01        2025-01      P3008            133        306466.58
8    2025-01-01        2025-01      P3009             62         42918.88
9    2025-01-01        2025-01      P3010             29         51123.81

In [ ]:
# ============================================================
# MONTHLY INVENTORY SUMMARY
# ============================================================

monthly_inventory = (
    inventory
    .groupby(
        "snapshot_month",
        as_index=False
    )
    .agg(
        total_inventory_units=("units_on_hand", "sum"),
        total_inventory_value=("inventory_value", "sum")
    )
)

print(monthly_inventory)

   snapshot_month  total_inventory_units  total_inventory_value
0         2025-01                   4036             4528345.34
1         2025-02                   4225             4990246.43
2         2025-03                   4174             5075556.15
3         2025-04                   4441             5266576.50
4         2025-05                   4157             4867295.84
5         2025-06                   4625             5464454.00
6         2025-07                   4078             4699496.25
7         2025-08                   4120             4990117.22
8         2025-09                   4142             4696089.16
9         2025-10                   3569             4067755.58
10        2025-11                   3921             4490406.42
11        2025-12                   4037             5007436.55
12        2026-01                   4158             4651957.74
13        2026-02                   4031             4805161.24
14        2026-03                   4232             4901212.08
15        2026-04                   3884             4613778.52
16        2026-05                   4401             4901716.15
17        2026-06                   4051             4701055.71
18        2026-07                   4155             4431759.36
19        2026-08                   4418             5239657.86

In [ ]:
# ============================================================
# LOAN PAYMENT TRANSFORMATION
# ============================================================

loan_payments["payment_date"] = pd.to_datetime(
    loan_payments["payment_date"],
    errors="coerce"
)

loan_payments["payment_month"] = (
    loan_payments["payment_date"]
    .dt.to_period("M")
    .astype(str)
)

print(
    loan_payments.head(10)
)


# ============================================================
# MONTHLY LOAN PAYMENT SUMMARY
# ============================================================

loan_payments["total_payment"] = pd.to_numeric(
    loan_payments["total_payment"],
    errors="coerce"
)

monthly_loan_payments = (
    loan_payments
    .groupby(
        "payment_month",
        as_index=False
    )
    .agg(
        total_loan_payments=("total_payment", "sum")
    )
)

print(monthly_loan_payments)

  payment_id loan_id payment_date  principal_paid  interest_paid  \
0   LP600001    L001   2025-02-01       134827.04       70000.00
1   LP600002    L001   2025-03-01       136006.77       68820.26
2   LP600003    L001   2025-04-01       137196.83       67630.20
3   LP600004    L001   2025-05-01       138397.31       66429.73
4   LP600005    L001   2025-06-01       139608.28       65218.76
5   LP600006    L001   2025-07-01       140829.86       63997.18
6   LP600007    L001   2025-08-01       142062.12       62764.92
7   LP600008    L001   2025-09-01       143305.16       61521.88
8   LP600009    L001   2025-10-01       144559.08       60267.96
9   LP600010    L001   2025-11-01       145823.97       59003.07

   total_payment payment_month
0      204827.04       2025-02
1      204827.04       2025-03
2      204827.04       2025-04
3      204827.04       2025-05
4      204827.04       2025-06
5      204827.04       2025-07
6      204827.04       2025-08
7      204827.04       2025-09
8      204827.04       2025-10
9      204827.04       2025-11
   payment_month  total_loan_payments
0        2025-02            204827.04
1        2025-03            204827.04
2        2025-04            204827.04
3        2025-05            204827.04
4        2025-06            204827.04
5        2025-07            369707.07
6        2025-08            369707.07
7        2025-09            369707.07
8        2025-10            369707.07
9        2025-11            369707.07
10       2025-12            369707.07
11       2026-01            465805.92
12       2026-02            465805.92
13       2026-03            465805.92
14       2026-04            465805.92
15       2026-05            465805.92
16       2026-06            465805.92
17       2026-07            465805.92
18       2026-08            465805.92

In [ ]:
# ============================================================
# FINAL CLEANING CHECK
# ============================================================

print("CLEANING CHECK")
print("=" * 60)

for table_name, df in tables.items():
    print(f"\n{table_name.upper()}")
    print("-" * 40)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

CLEANING CHECK
============================================================

CUSTOMERS
----------------------------------------
Rows: 120
Columns: 5
Missing values: 0
Duplicate rows: 0

VENDORS
----------------------------------------
Rows: 45
Columns: 4
Missing values: 0
Duplicate rows: 0

PRODUCTS
----------------------------------------
Rows: 60
Columns: 5
Missing values: 0
Duplicate rows: 0

SALES_INVOICES
----------------------------------------
Rows: 5000
Columns: 17
Missing values: 994
Duplicate rows: 0

VENDOR_INVOICES
----------------------------------------
Rows: 2200
Columns: 12
Missing values: 450
Duplicate rows: 0

OPERATING_EXPENSES
----------------------------------------
Rows: 160
Columns: 5
Missing values: 0
Duplicate rows: 0

PAYROLL
----------------------------------------
Rows: 20
Columns: 7
Missing values: 0
Duplicate rows: 0

LOANS
----------------------------------------
Rows: 3
Columns: 6
Missing values: 0
Duplicate rows: 0

LOAN_PAYMENTS
----------------------------------------
Rows: 41
Columns: 7
Missing values: 0
Duplicate rows: 0

BANK_TRANSACTIONS
----------------------------------------
Rows: 6700
Columns: 8
Missing values: 0
Duplicate rows: 0

INVENTORY_SNAPSHOTS
----------------------------------------
Rows: 1200
Columns: 6
Missing values: 0
Duplicate rows: 0

In [16]:
# ============================================================
# CREATE TABLE DICTIONARY FOR FINAL CLEANING CHECK
# ============================================================

# ============================================================
# CREATE TABLE DICTIONARY FOR FINAL CLEANING CHECK
# ============================================================

tables = {
    "customers": customers,
    "vendors": vendors,
    "products": products,
    "sales_invoices": sales,
    "vendor_invoices": vendor_invoices,
    "operating_expenses": operating_expenses,
    "payroll": payroll,
    "loans": loans,
    "loan_payments": loan_payments,
    "bank_transactions": bank_transactions,
    "inventory_snapshots": inventory
}

print("Tables loaded:", len(tables))
print(list(tables.keys()))

Tables loaded: 11
['customers', 'vendors', 'products', 'sales_invoices', 'vendor_invoices', 'operating_expenses', 'payroll', 'loans', 'loan_payments', 'bank_transactions', 'inventory_snapshots']

In [ ]:
# FINAL DATA QUALITY SUMMARY

summary = []

for table_name, df in tables.items():
    summary.append({
        "Table": table_name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Missing Values": int(df.isnull().sum().sum()),
        "Duplicate Rows": int(df.duplicated().sum())
    })

quality_summary = pd.DataFrame(summary)

quality_summary

                  Table  Rows  Columns  Missing Values  Duplicate Rows
0             customers   120        5               0               0
1               vendors    45        4               0               0
2              products    60        5               0               0
3        sales_invoices  5000       17             994               0
4       vendor_invoices  2200       12             450               0
5    operating_expenses   160        5               0               0
6               payroll    20        7               0               0
7                 loans     3        6               0               0
8         loan_payments    41        7               0               0
9     bank_transactions  6700        8               0               0
10  inventory_snapshots  1200        6               0               0

In [ ]:
for table_name in ["sales_invoices", "vendor_invoices"]:
    print("\n" + "=" * 60)
    print(table_name.upper())
    print("=" * 60)

    missing = tables[table_name].isnull().sum()
    print(missing[missing > 0])

============================================================
SALES_INVOICES
============================================================
payment_date    497
days_to_pay     497
dtype: int64

============================================================
VENDOR_INVOICES
============================================================
payment_date    225
days_to_pay     225
dtype: int64

In [ ]:
print("SALES INVOICES PAYMENT STATUS")
print(sales["payment_status"].value_counts(dropna=False))

print("\nVENDOR INVOICES PAYMENT STATUS")
print(vendor_invoices["payment_status"].value_counts(dropna=False))

SALES INVOICES PAYMENT STATUS
payment_status
Paid           4503
Outstanding     497
Name: count, dtype: int64

VENDOR INVOICES PAYMENT STATUS
payment_status
Paid           1975
Outstanding     225
Name: count, dtype: int64

In [ ]:
# VALIDATE PAYMENT DATE VS PAYMENT STATUS

print("SALES INVOICES")
print("=" * 50)

print(
    "Outstanding with missing payment date:",
    ((sales["payment_status"] == "Outstanding") &
     (sales["payment_date"].isna())).sum()
)

print(
    "Paid with missing payment date:",
    ((sales["payment_status"] == "Paid") &
     (sales["payment_date"].isna())).sum()
)


print("\nVENDOR INVOICES")
print("=" * 50)

print(
    "Outstanding with missing payment date:",
    ((vendor_invoices["payment_status"] == "Outstanding") &
     (vendor_invoices["payment_date"].isna())).sum()
)

print(
    "Paid with missing payment date:",
    ((vendor_invoices["payment_status"] == "Paid") &
     (vendor_invoices["payment_date"].isna())).sum()
)

SALES INVOICES
==================================================
Outstanding with missing payment date: 497
Paid with missing payment date: 0

VENDOR INVOICES
==================================================
Outstanding with missing payment date: 225
Paid with missing payment date: 0

In [12]:
for table_name, df in tables.items():
    print("\n" + table_name.upper())
    print(list(df.columns))

CUSTOMERS
['customer_id', 'customer_name', 'customer_segment', 'region', 'credit_terms_days']

VENDORS
['vendor_id', 'vendor_name', 'vendor_category', 'payment_terms_days']

PRODUCTS
['product_id', 'product_name', 'category', 'unit_cost', 'selling_price']

SALES_INVOICES
['invoice_id', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'discount_pct', 'unit_price', 'gross_amount', 'discount_amount', 'net_invoice_amount', 'due_date', 'payment_date', 'payment_status', 'days_to_pay', 'days_late', 'invoice_month', 'ageing_bucket']

VENDOR_INVOICES
['vendor_invoice_id', 'invoice_date', 'vendor_id', 'expense_category', 'invoice_amount', 'due_date', 'payment_date', 'payment_status', 'days_to_pay', 'days_late', 'invoice_month', 'ageing_bucket']

OPERATING_EXPENSES
['expense_id', 'expense_date', 'expense_category', 'amount', 'expense_month']

PAYROLL
['payroll_id', 'pay_date', 'gross_payroll', 'tax_and_deductions', 'net_payroll']

LOANS
['loan_id', 'loan_type', 'principal_amount', 'annual_interest_rate', 'start_date', 'tenure_months']

LOAN_PAYMENTS
['payment_id', 'loan_id', 'payment_date', 'principal_paid', 'interest_paid', 'total_payment']

BANK_TRANSACTIONS
['bank_txn_id', 'transaction_date', 'transaction_type', 'reference_id', 'amount']

INVENTORY_SNAPSHOTS
['inventory_snapshot_id', 'snapshot_date', 'product_id', 'units_on_hand', 'inventory_value']

In [13]:
print(list(sales.columns))

['invoice_id', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'discount_pct', 'unit_price', 'gross_amount', 'discount_amount', 'net_invoice_amount', 'due_date', 'payment_date', 'payment_status', 'days_to_pay', 'days_late', 'invoice_month', 'ageing_bucket']

In [14]:
for col in sales.columns:
    print(col)

invoice_id
invoice_date
customer_id
product_id
quantity
discount_pct
unit_price
gross_amount
discount_amount
net_invoice_amount
due_date
payment_date
payment_status
days_to_pay
days_late
invoice_month
ageing_bucket

In [18]:
import pandas as pd
from sqlalchemy import create_engine

# MySQL connection
engine = create_engine(
    "mysql+pymysql://root:manager@127.0.0.1:3306/cashflowiq"
)

print("MySQL connection created successfully!")

MySQL connection created successfully!

In [17]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in d:\aanaconda\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: greenlet>=1 in d:\aanaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\aanaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [11]:
# Load cleaned customers data
customers_df = pd.read_csv("../Data/customers.csv")

print("Customers loaded:", len(customers_df))
customers_df.head()

Customers loaded: 120

  customer_id customer_name customer_segment region  credit_terms_days
0       C1001  Customer 001              SMB   East                 60
1       C1002  Customer 002       Mid-Market   East                 60
2       C1003  Customer 003       Mid-Market   West                 60
3       C1004  Customer 004              SMB   West                 30
4       C1005  Customer 005       Enterprise   West                 15

In [20]:
import os

print(os.getcwd())
print(os.listdir(".."))

d:\DATA ANALYST PROJECTS\Analytics_Projects\CashFlowIQ\Python
['Clean_Data', 'Data', 'Documentation', 'PowerBI', 'Python', 'README.txt', 'SQL']

In [21]:
import os

print(os.listdir("../Clean_Data"))

[]

In [22]:
import os

print(os.listdir("../Data"))

['bank_transactions.csv', 'customers.csv', 'inventory_snapshots.csv', 'loans.csv', 'loan_payments.csv', 'operating_expenses.csv', 'payroll.csv', 'products.csv', 'sales_invoices.csv', 'vendors.csv', 'vendor_invoices.csv']

In [23]:
customers_df = pd.read_csv("../Data/customers.csv")

print("Customers loaded:", len(customers_df))
customers_df.head()

Customers loaded: 120

  customer_id customer_name customer_segment region  credit_terms_days
0       C1001  Customer 001              SMB   East                 60
1       C1002  Customer 002       Mid-Market   East                 60
2       C1003  Customer 003       Mid-Market   West                 60
3       C1004  Customer 004              SMB   West                 30
4       C1005  Customer 005       Enterprise   West                 15

In [24]:
# Load all CSV files

customers_df = pd.read_csv("../Data/customers.csv")
vendors_df = pd.read_csv("../Data/vendors.csv")
products_df = pd.read_csv("../Data/products.csv")
sales_invoices_df = pd.read_csv("../Data/sales_invoices.csv")
vendor_invoices_df = pd.read_csv("../Data/vendor_invoices.csv")
operating_expenses_df = pd.read_csv("../Data/operating_expenses.csv")
payroll_df = pd.read_csv("../Data/payroll.csv")
loans_df = pd.read_csv("../Data/loans.csv")
loan_payments_df = pd.read_csv("../Data/loan_payments.csv")
bank_transactions_df = pd.read_csv("../Data/bank_transactions.csv")
inventory_snapshots_df = pd.read_csv("../Data/inventory_snapshots.csv")

print("All tables loaded successfully!")

print("Customers:", len(customers_df))
print("Vendors:", len(vendors_df))
print("Products:", len(products_df))
print("Sales Invoices:", len(sales_invoices_df))
print("Vendor Invoices:", len(vendor_invoices_df))
print("Operating Expenses:", len(operating_expenses_df))
print("Payroll:", len(payroll_df))
print("Loans:", len(loans_df))
print("Loan Payments:", len(loan_payments_df))
print("Bank Transactions:", len(bank_transactions_df))
print("Inventory Snapshots:", len(inventory_snapshots_df))

All tables loaded successfully!
Customers: 120
Vendors: 45
Products: 60
Sales Invoices: 5000
Vendor Invoices: 2200
Operating Expenses: 160
Payroll: 20
Loans: 3
Loan Payments: 41
Bank Transactions: 6700
Inventory Snapshots: 1200

In [2]:
import pymysql
import getpass

password = getpass.getpass("Enter MySQL Password: ")

connection = pymysql.connect(
    host="127.0.0.1",
    user="root",
    password=password,
    database="cashflowiq"
)

print("MySQL connection successful!")

MySQL connection successful!

In [27]:
cursor.execute("SELECT COUNT(*) FROM customers")
print("Customers in MySQL:", cursor.fetchone()[0])

Customers in MySQL: 120

In [29]:
cursor.execute("SELECT COUNT(*) FROM vendors")
print("Vendors in MySQL:", cursor.fetchone()[0])

Vendors in MySQL: 45

In [31]:
cursor.execute("SELECT COUNT(*) FROM products")
print("Products in MySQL:", cursor.fetchone()[0])

Products in MySQL: 60

In [41]:
cursor.execute("SELECT COUNT(*) FROM sales_invoices")
print("Sales Invoices in MySQL:", cursor.fetchone()[0])

Sales Invoices in MySQL: 5000

In [35]:
print(sales_invoices_df.columns.tolist())

['invoice_id', 'invoice_date', 'customer_id', 'product_id', 'quantity', 'discount_pct', 'unit_price', 'gross_amount', 'discount_amount', 'net_invoice_amount', 'due_date', 'payment_date']

In [36]:
sales_invoices_df["payment_status"] = sales_invoices_df["payment_date"].apply(
    lambda x: "Paid" if pd.notna(x) else "Outstanding"
)

print(sales_invoices_df["payment_status"].value_counts())

payment_status
Paid           4503
Outstanding     497
Name: count, dtype: int64

In [39]:
connection.rollback()

In [40]:
sales_invoice_sql = """
INSERT INTO sales_invoices
(invoice_id, invoice_date, customer_id, product_id, quantity,
discount_pct, unit_price, gross_amount, discount_amount,
net_invoice_amount, due_date, payment_date, payment_status)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

sales_invoice_columns = [
    "invoice_id",
    "invoice_date",
    "customer_id",
    "product_id",
    "quantity",
    "discount_pct",
    "unit_price",
    "gross_amount",
    "discount_amount",
    "net_invoice_amount",
    "due_date",
    "payment_date",
    "payment_status"
]

sales_invoice_data = []

for row in sales_invoices_df[sales_invoice_columns].itertuples(
    index=False, name=None
):
    cleaned_row = []

    for value in row:
        if pd.isna(value):
            cleaned_row.append(None)
        elif isinstance(value, pd.Timestamp):
            cleaned_row.append(value.to_pydatetime())
        else:
            cleaned_row.append(value)

    sales_invoice_data.append(tuple(cleaned_row))

cursor.executemany(sales_invoice_sql, sales_invoice_data)
connection.commit()

print("Sales Invoices inserted successfully:", cursor.rowcount)

Sales Invoices inserted successfully: 5000

In [44]:
vendor_invoice_sql = """
INSERT INTO vendor_invoices
(vendor_invoice_id, invoice_date, vendor_id, expense_category,
invoice_amount, due_date, payment_date, payment_status,
days_to_pay, days_late, invoice_month, ageing_bucket)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

vendor_invoice_columns = [
    "vendor_invoice_id",
    "invoice_date",
    "vendor_id",
    "expense_category",
    "invoice_amount",
    "due_date",
    "payment_date",
    "payment_status",
    "days_to_pay",
    "days_late",
    "invoice_month",
    "ageing_bucket"
]

vendor_invoice_data = []

for row in vendor_invoices_df[vendor_invoice_columns].itertuples(
    index=False, name=None
):
    cleaned_row = []

    for value in row:
        if pd.isna(value):
            cleaned_row.append(None)
        elif isinstance(value, pd.Timestamp):
            cleaned_row.append(value.to_pydatetime())
        else:
            cleaned_row.append(value)

    vendor_invoice_data.append(tuple(cleaned_row))

cursor.executemany(vendor_invoice_sql, vendor_invoice_data)
connection.commit()

print("Vendor Invoices inserted successfully:", cursor.rowcount)

Vendor Invoices inserted successfully: 2200

In [43]:
# Create derived columns for Vendor Invoices

vendor_invoices_df["invoice_date"] = pd.to_datetime(
    vendor_invoices_df["invoice_date"], errors="coerce"
)

vendor_invoices_df["due_date"] = pd.to_datetime(
    vendor_invoices_df["due_date"], errors="coerce"
)

vendor_invoices_df["payment_date"] = pd.to_datetime(
    vendor_invoices_df["payment_date"], errors="coerce"
)

# Payment status
vendor_invoices_df["payment_status"] = vendor_invoices_df["payment_date"].apply(
    lambda x: "Paid" if pd.notna(x) else "Outstanding"
)

# Days to pay
vendor_invoices_df["days_to_pay"] = (
    vendor_invoices_df["payment_date"] - vendor_invoices_df["invoice_date"]
).dt.days

# Days late
vendor_invoices_df["days_late"] = (
    vendor_invoices_df["payment_date"] - vendor_invoices_df["due_date"]
).dt.days

vendor_invoices_df["days_late"] = (
    vendor_invoices_df["days_late"]
    .fillna(0)
    .clip(lower=0)
    .astype(int)
)

# Invoice month
vendor_invoices_df["invoice_month"] = (
    vendor_invoices_df["invoice_date"].dt.to_period("M").astype(str)
)

# Ageing bucket
vendor_invoices_df["ageing_bucket"] = pd.cut(
    vendor_invoices_df["days_late"],
    bins=[-1, 0, 30, 60, 90, float("inf")],
    labels=["Current", "1-30 Days", "31-60 Days", "61-90 Days", "90+ Days"]
)

print("Vendor invoice derived columns created successfully!")
print(vendor_invoices_df[
    [
        "payment_status",
        "days_to_pay",
        "days_late",
        "invoice_month",
        "ageing_bucket"
    ]
].head())

Vendor invoice derived columns created successfully!
  payment_status  days_to_pay  days_late invoice_month ageing_bucket
0           Paid         30.0          0       2026-01       Current
1           Paid         58.0         13       2026-03     1-30 Days
2           Paid         31.0          1       2026-05     1-30 Days
3           Paid         36.0          6       2025-07     1-30 Days
4           Paid         30.0          0       2026-06       Current

In [45]:
cursor.execute("SELECT COUNT(*) FROM vendor_invoices")
print("Vendor Invoices in MySQL:", cursor.fetchone()[0])

Vendor Invoices in MySQL: 2200

In [46]:
print(operating_expenses_df.columns.tolist())
print("Rows:", len(operating_expenses_df))

['expense_id', 'expense_date', 'expense_category', 'amount']
Rows: 160

In [47]:
operating_expense_sql = """
INSERT INTO operating_expenses
(expense_id, expense_date, expense_category, amount)
VALUES (%s, %s, %s, %s)
"""

operating_expense_data = [
    tuple(row)
    for row in operating_expenses_df[
        ["expense_id", "expense_date", "expense_category", "amount"]
    ].itertuples(index=False, name=None)
]

cursor.executemany(operating_expense_sql, operating_expense_data)
connection.commit()

print("Operating Expenses inserted successfully:", cursor.rowcount)

Operating Expenses inserted successfully: 160

In [48]:
cursor.execute("SELECT COUNT(*) FROM operating_expenses")
print("Operating Expenses in MySQL:", cursor.fetchone()[0])

Operating Expenses in MySQL: 160

In [49]:
print(payroll_df.columns.tolist())
print("Rows:", len(payroll_df))

['payroll_id', 'pay_date', 'gross_payroll', 'tax_and_deductions', 'net_payroll']
Rows: 20

In [50]:
payroll_sql = """
INSERT INTO payroll
(payroll_id, pay_date, gross_payroll, tax_and_deductions, net_payroll)
VALUES (%s, %s, %s, %s, %s)
"""

payroll_data = [
    tuple(row)
    for row in payroll_df[
        ["payroll_id", "pay_date", "gross_payroll", "tax_and_deductions", "net_payroll"]
    ].itertuples(index=False, name=None)
]

cursor.executemany(payroll_sql, payroll_data)
connection.commit()

print("Payroll inserted successfully:", cursor.rowcount)

Payroll inserted successfully: 20

In [51]:
cursor.execute("SELECT COUNT(*) FROM payroll")
print("Payroll in MySQL:", cursor.fetchone()[0])

Payroll in MySQL: 20

In [52]:
print(loans_df.columns.tolist())
print("Rows:", len(loans_df))

['loan_id', 'loan_type', 'principal_amount', 'annual_interest_rate', 'start_date', 'tenure_months']
Rows: 3

In [53]:
loan_sql = """
INSERT INTO loans
(loan_id, loan_type, principal_amount, annual_interest_rate, start_date, tenure_months)
VALUES (%s, %s, %s, %s, %s, %s)
"""

loan_data = [
    tuple(row)
    for row in loans_df[
        [
            "loan_id",
            "loan_type",
            "principal_amount",
            "annual_interest_rate",
            "start_date",
            "tenure_months"
        ]
    ].itertuples(index=False, name=None)
]

cursor.executemany(loan_sql, loan_data)
connection.commit()

print("Loans inserted successfully:", cursor.rowcount)

Loans inserted successfully: 3

In [54]:
cursor.execute("SELECT COUNT(*) FROM loans")
print("Loans in MySQL:", cursor.fetchone()[0])

Loans in MySQL: 3

In [55]:
print(loan_payments_df.columns.tolist())
print("Rows:", len(loan_payments_df))

['payment_id', 'loan_id', 'payment_date', 'principal_paid', 'interest_paid', 'total_payment']
Rows: 41

In [56]:
loan_payment_sql = """
INSERT INTO loan_payments
(loan_payment_id, loan_id, payment_date, principal_paid, interest_paid, total_payment, payment_status)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

loan_payment_data = [
    (
        row.payment_id,
        row.loan_id,
        row.payment_date,
        row.principal_paid,
        row.interest_paid,
        row.total_payment,
        "Paid"
    )
    for row in loan_payments_df.itertuples(index=False)
]

cursor.executemany(loan_payment_sql, loan_payment_data)
connection.commit()

print("Loan Payments inserted successfully:", cursor.rowcount)

Loan Payments inserted successfully: 41

In [57]:
cursor.execute("SELECT COUNT(*) FROM loan_payments")
print("Loan Payments in MySQL:", cursor.fetchone()[0])

Loan Payments in MySQL: 41

In [58]:
print(bank_transactions_df.columns.tolist())
print("Rows:", len(bank_transactions_df))

['bank_txn_id', 'transaction_date', 'transaction_type', 'reference_id', 'amount']
Rows: 6700

In [59]:
bank_transaction_sql = """
INSERT INTO bank_transactions
(bank_txn_id, transaction_date, transaction_type, reference_id, amount)
VALUES (%s, %s, %s, %s, %s)
"""

bank_transaction_data = [
    tuple(row)
    for row in bank_transactions_df[
        ["bank_txn_id", "transaction_date", "transaction_type", "reference_id", "amount"]
    ].itertuples(index=False, name=None)
]

cursor.executemany(bank_transaction_sql, bank_transaction_data)
connection.commit()

print("Bank Transactions inserted successfully:", cursor.rowcount)

Bank Transactions inserted successfully: 6700

In [60]:
cursor.execute("SELECT COUNT(*) FROM bank_transactions")
print("Bank Transactions in MySQL:", cursor.fetchone()[0])

Bank Transactions in MySQL: 6700

In [61]:
print(inventory_snapshots_df.columns.tolist())
print("Rows:", len(inventory_snapshots_df))

['inventory_snapshot_id', 'snapshot_date', 'product_id', 'units_on_hand', 'inventory_value']
Rows: 1200

In [62]:
inventory_snapshot_sql = """
INSERT INTO inventory_snapshots
(inventory_snapshot_id, snapshot_date, product_id, units_on_hand, inventory_value)
VALUES (%s, %s, %s, %s, %s)
"""

inventory_snapshot_data = [
    tuple(row)
    for row in inventory_snapshots_df[
        [
            "inventory_snapshot_id",
            "snapshot_date",
            "product_id",
            "units_on_hand",
            "inventory_value"
        ]
    ].itertuples(index=False, name=None)
]

cursor.executemany(
    inventory_snapshot_sql,
    inventory_snapshot_data
)

connection.commit()

print(
    "Inventory Snapshots inserted successfully:",
    cursor.rowcount
)

Inventory Snapshots inserted successfully: 1200

In [63]:
cursor.execute("SELECT COUNT(*) FROM inventory_snapshots")
print(
    "Inventory Snapshots in MySQL:",
    cursor.fetchone()[0]
)

Inventory Snapshots in MySQL: 1200

In [17]:
tables = [
    "customers",
    "vendors",
    "products",
    "sales_invoices",
    "vendor_invoices",
    "operating_expenses",
    "payroll",
    "loans",
    "loan_payments",
    "bank_transactions",
    "inventory_snapshots"
]

for table in tables:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    print(f"{table}: {count}")

customers: 120
vendors: 45
products: 60
sales_invoices: 5000
vendor_invoices: 2200
operating_expenses: 160
payroll: 20
loans: 3
loan_payments: 41
bank_transactions: 6700
inventory_snapshots: 1200

In [65]:
print("CUSTOMERS DATA QUALITY CHECK")
print("=" * 40)

print("Duplicate customer IDs:",
      customers_df["customer_id"].duplicated().sum())

print("Missing values:")
print(customers_df.isnull().sum())

CUSTOMERS DATA QUALITY CHECK
========================================
Duplicate customer IDs: 0
Missing values:
customer_id          0
customer_name        0
customer_segment     0
region               0
credit_terms_days    0
dtype: int64

In [66]:
print("VENDORS DATA QUALITY CHECK")
print("=" * 40)

print("Duplicate vendor IDs:",
      vendors_df["vendor_id"].duplicated().sum())

print("Missing values:")
print(vendors_df.isnull().sum())

VENDORS DATA QUALITY CHECK
========================================
Duplicate vendor IDs: 0
Missing values:
vendor_id             0
vendor_name           0
vendor_category       0
payment_terms_days    0
dtype: int64

In [67]:
print("PRODUCTS DATA QUALITY CHECK")
print("=" * 40)

print("Duplicate product IDs:",
      products_df["product_id"].duplicated().sum())

print("Missing values:")
print(products_df.isnull().sum())

PRODUCTS DATA QUALITY CHECK
========================================
Duplicate product IDs: 0
Missing values:
product_id       0
product_name     0
category         0
unit_cost        0
selling_price    0
dtype: int64

In [68]:
# ==========================================
# REMAINING TABLES - DATA QUALITY CHECK
# ==========================================

quality_checks = {
    "Sales Invoices": (sales_invoices_df, "invoice_id"),
    "Vendor Invoices": (vendor_invoices_df, "vendor_invoice_id"),
    "Operating Expenses": (operating_expenses_df, "expense_id"),
    "Payroll": (payroll_df, "payroll_id"),
    "Loans": (loans_df, "loan_id"),
    "Loan Payments": (loan_payments_df, "payment_id"),
    "Bank Transactions": (bank_transactions_df, "bank_txn_id"),
    "Inventory Snapshots": (inventory_snapshots_df, "inventory_snapshot_id")
}

for table_name, (df, id_column) in quality_checks.items():

    print("\n" + "=" * 60)
    print(f"{table_name.upper()} DATA QUALITY CHECK")
    print("=" * 60)

    # Row count
    print("Rows:", len(df))

    # Duplicate primary IDs
    print(
        f"Duplicate {id_column}:",
        df[id_column].duplicated().sum()
    )

    # Missing values
    missing = df.isnull().sum()

    if missing.sum() == 0:
        print("Missing values: 0")
    else:
        print("Missing values:")
        print(missing[missing > 0])

============================================================
SALES INVOICES DATA QUALITY CHECK
============================================================
Rows: 5000
Duplicate invoice_id: 0
Missing values:
payment_date    497
dtype: int64

============================================================
VENDOR INVOICES DATA QUALITY CHECK
============================================================
Rows: 2200
Duplicate vendor_invoice_id: 0
Missing values:
payment_date    225
days_to_pay     225
dtype: int64

============================================================
OPERATING EXPENSES DATA QUALITY CHECK
============================================================
Rows: 160
Duplicate expense_id: 0
Missing values: 0

============================================================
PAYROLL DATA QUALITY CHECK
============================================================
Rows: 20
Duplicate payroll_id: 0
Missing values: 0

============================================================
LOANS DATA QUALITY CHECK
============================================================
Rows: 3
Duplicate loan_id: 0
Missing values: 0

============================================================
LOAN PAYMENTS DATA QUALITY CHECK
============================================================
Rows: 41
Duplicate payment_id: 0
Missing values: 0

============================================================
BANK TRANSACTIONS DATA QUALITY CHECK
============================================================
Rows: 6700
Duplicate bank_txn_id: 0
Missing values: 0

============================================================
INVENTORY SNAPSHOTS DATA QUALITY CHECK
============================================================
Rows: 1200
Duplicate inventory_snapshot_id: 0
Missing values: 0

In [69]:
# ==========================================
# SALES INVOICES - DATA TRANSFORMATION
# ==========================================

# Make sure date columns are proper datetime
sales_invoices_df["invoice_date"] = pd.to_datetime(
    sales_invoices_df["invoice_date"],
    errors="coerce"
)

sales_invoices_df["due_date"] = pd.to_datetime(
    sales_invoices_df["due_date"],
    errors="coerce"
)

sales_invoices_df["payment_date"] = pd.to_datetime(
    sales_invoices_df["payment_date"],
    errors="coerce"
)

# Payment status
sales_invoices_df["payment_status"] = sales_invoices_df[
    "payment_date"
].apply(
    lambda x: "Paid" if pd.notna(x) else "Outstanding"
)

# Days taken to pay
sales_invoices_df["days_to_pay"] = (
    sales_invoices_df["payment_date"]
    - sales_invoices_df["invoice_date"]
).dt.days

# Days late
sales_invoices_df["days_late"] = (
    sales_invoices_df["payment_date"]
    - sales_invoices_df["due_date"]
).dt.days

# Invoice month
sales_invoices_df["invoice_month"] = (
    sales_invoices_df["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

# Ageing bucket
sales_invoices_df["ageing_bucket"] = pd.cut(
    sales_invoices_df["days_late"],
    bins=[-float("inf"), 0, 30, 60, 90, float("inf")],
    labels=[
        "Current",
        "1-30 Days",
        "31-60 Days",
        "61-90 Days",
        "90+ Days"
    ]
)

print("Sales Invoice transformations completed successfully!")

print(
    sales_invoices_df[
        [
            "payment_status",
            "days_to_pay",
            "days_late",
            "invoice_month",
            "ageing_bucket"
        ]
    ].head()
)

Sales Invoice transformations completed successfully!
  payment_status  days_to_pay  days_late invoice_month ageing_bucket
0           Paid         23.0        8.0       2025-04     1-30 Days
1           Paid         28.0       13.0       2026-01     1-30 Days
2           Paid         30.0        0.0       2026-06       Current
3           Paid         45.0       15.0       2025-12     1-30 Days
4           Paid         56.0       11.0       2025-10     1-30 Days

In [70]:
# ==========================================
# VENDOR INVOICES - DATA TRANSFORMATION
# ==========================================

# Convert date columns
vendor_invoices_df["invoice_date"] = pd.to_datetime(
    vendor_invoices_df["invoice_date"],
    errors="coerce"
)

vendor_invoices_df["due_date"] = pd.to_datetime(
    vendor_invoices_df["due_date"],
    errors="coerce"
)

vendor_invoices_df["payment_date"] = pd.to_datetime(
    vendor_invoices_df["payment_date"],
    errors="coerce"
)

# Payment status
vendor_invoices_df["payment_status"] = vendor_invoices_df[
    "payment_date"
].apply(
    lambda x: "Paid" if pd.notna(x) else "Outstanding"
)

# Days taken to pay
vendor_invoices_df["days_to_pay"] = (
    vendor_invoices_df["payment_date"]
    - vendor_invoices_df["invoice_date"]
).dt.days

# Days late
vendor_invoices_df["days_late"] = (
    vendor_invoices_df["payment_date"]
    - vendor_invoices_df["due_date"]
).dt.days

# Invoice month
vendor_invoices_df["invoice_month"] = (
    vendor_invoices_df["invoice_date"]
    .dt.to_period("M")
    .astype(str)
)

# Ageing bucket
vendor_invoices_df["ageing_bucket"] = pd.cut(
    vendor_invoices_df["days_late"],
    bins=[-float("inf"), 0, 30, 60, 90, float("inf")],
    labels=[
        "Current",
        "1-30 Days",
        "31-60 Days",
        "61-90 Days",
        "90+ Days"
    ]
)

print("Vendor Invoice transformations completed successfully!")

print(
    vendor_invoices_df[
        [
            "payment_status",
            "days_to_pay",
            "days_late",
            "invoice_month",
            "ageing_bucket"
        ]
    ].head()
)

Vendor Invoice transformations completed successfully!
  payment_status  days_to_pay  days_late invoice_month ageing_bucket
0           Paid         30.0        0.0       2026-01       Current
1           Paid         58.0       13.0       2026-03     1-30 Days
2           Paid         31.0        1.0       2026-05     1-30 Days
3           Paid         36.0        6.0       2025-07     1-30 Days
4           Paid         30.0        0.0       2026-06       Current

In [71]:
# ==========================================
# OPERATING EXPENSES - DATA TRANSFORMATION
# ==========================================

# Convert date column
operating_expenses_df["expense_date"] = pd.to_datetime(
    operating_expenses_df["expense_date"],
    errors="coerce"
)

# Expense month
operating_expenses_df["expense_month"] = (
    operating_expenses_df["expense_date"]
    .dt.to_period("M")
    .astype(str)
)

# Expense year
operating_expenses_df["expense_year"] = (
    operating_expenses_df["expense_date"]
    .dt.year
)

# Expense category cleanup
operating_expenses_df["expense_category"] = (
    operating_expenses_df["expense_category"]
    .astype(str)
    .str.strip()
    .str.title()
)

# Amount as numeric
operating_expenses_df["amount"] = pd.to_numeric(
    operating_expenses_df["amount"],
    errors="coerce"
)

print("Operating Expenses transformations completed successfully!")

print(
    operating_expenses_df[
        [
            "expense_date",
            "expense_category",
            "amount",
            "expense_month",
            "expense_year"
        ]
    ].head()
)

Operating Expenses transformations completed successfully!
  expense_date expense_category     amount expense_month  expense_year
0   2025-01-01          Payroll  916245.95       2025-01          2025
1   2025-01-01             Rent  185869.91       2025-01          2025
2   2025-01-01        Utilities   63746.62       2025-01          2025
3   2025-01-01        Marketing  165352.65       2025-01          2025
4   2025-01-01         Software   88814.48       2025-01          2025

In [72]:
# ==========================================
# PAYROLL - DATA TRANSFORMATION
# ==========================================

# Convert pay date
payroll_df["pay_date"] = pd.to_datetime(
    payroll_df["pay_date"],
    errors="coerce"
)

# Convert numeric columns
payroll_df["gross_payroll"] = pd.to_numeric(
    payroll_df["gross_payroll"],
    errors="coerce"
)

payroll_df["tax_and_deductions"] = pd.to_numeric(
    payroll_df["tax_and_deductions"],
    errors="coerce"
)

payroll_df["net_payroll"] = pd.to_numeric(
    payroll_df["net_payroll"],
    errors="coerce"
)

# Payroll month
payroll_df["pay_month"] = (
    payroll_df["pay_date"]
    .dt.to_period("M")
    .astype(str)
)

# Payroll year
payroll_df["pay_year"] = (
    payroll_df["pay_date"]
    .dt.year
)

print("Payroll transformations completed successfully!")

print(
    payroll_df[
        [
            "pay_date",
            "gross_payroll",
            "tax_and_deductions",
            "net_payroll",
            "pay_month",
            "pay_year"
        ]
    ].head()
)

Payroll transformations completed successfully!
    pay_date  gross_payroll  tax_and_deductions  net_payroll pay_month  \
0 2025-01-28      851940.78           107052.14    744888.64   2025-01
1 2025-02-28      857492.39            97790.62    759701.77   2025-02
2 2025-03-28      857181.35            85842.59    771338.76   2025-03
3 2025-04-28      861824.28            99841.21    761983.07   2025-04
4 2025-05-28      911705.53           120514.39    791191.14   2025-05

   pay_year
0      2025
1      2025
2      2025
3      2025
4      2025

In [73]:
# ==========================================
# LOANS - DATA TRANSFORMATION
# ==========================================

# Convert start date
loans_df["start_date"] = pd.to_datetime(
    loans_df["start_date"],
    errors="coerce"
)

# Convert numeric columns
loans_df["principal_amount"] = pd.to_numeric(
    loans_df["principal_amount"],
    errors="coerce"
)

loans_df["annual_interest_rate"] = pd.to_numeric(
    loans_df["annual_interest_rate"],
    errors="coerce"
)

loans_df["tenure_months"] = pd.to_numeric(
    loans_df["tenure_months"],
    errors="coerce"
)

# Loan month
loans_df["loan_month"] = (
    loans_df["start_date"]
    .dt.to_period("M")
    .astype(str)
)

# Loan year
loans_df["loan_year"] = (
    loans_df["start_date"]
    .dt.year
)

print("Loans transformations completed successfully!")

print(
    loans_df[
        [
            "loan_id",
            "loan_type",
            "principal_amount",
            "annual_interest_rate",
            "start_date",
            "tenure_months",
            "loan_month",
            "loan_year"
        ]
    ].head()
)

Loans transformations completed successfully!
  loan_id             loan_type  principal_amount  annual_interest_rate  \
0    L001             Term Loan           8000000                 0.105
1    L002  Working Capital Loan           5000000                 0.115
2    L003        Equipment Loan           3000000                 0.095

  start_date  tenure_months loan_month  loan_year
0 2025-02-01             48    2025-02       2025
1 2025-07-01             36    2025-07       2025
2 2026-01-01             36    2026-01       2026

In [74]:
# ==========================================
# LOAN PAYMENTS - DATA TRANSFORMATION
# ==========================================

# Convert payment date
loan_payments_df["payment_date"] = pd.to_datetime(
    loan_payments_df["payment_date"],
    errors="coerce"
)

# Convert numeric columns
loan_payments_df["principal_paid"] = pd.to_numeric(
    loan_payments_df["principal_paid"],
    errors="coerce"
)

loan_payments_df["interest_paid"] = pd.to_numeric(
    loan_payments_df["interest_paid"],
    errors="coerce"
)

loan_payments_df["total_payment"] = pd.to_numeric(
    loan_payments_df["total_payment"],
    errors="coerce"
)

# Payment month
loan_payments_df["payment_month"] = (
    loan_payments_df["payment_date"]
    .dt.to_period("M")
    .astype(str)
)

# Payment year
loan_payments_df["payment_year"] = (
    loan_payments_df["payment_date"]
    .dt.year
)

# Payment status
loan_payments_df["payment_status"] = "Paid"

print("Loan Payments transformations completed successfully!")

print(
    loan_payments_df[
        [
            "payment_id",
            "loan_id",
            "payment_date",
            "principal_paid",
            "interest_paid",
            "total_payment",
            "payment_status",
            "payment_month",
            "payment_year"
        ]
    ].head()
)

Loan Payments transformations completed successfully!
  payment_id loan_id payment_date  principal_paid  interest_paid  \
0   LP600001    L001   2025-02-01       134827.04       70000.00
1   LP600002    L001   2025-03-01       136006.77       68820.26
2   LP600003    L001   2025-04-01       137196.83       67630.20
3   LP600004    L001   2025-05-01       138397.31       66429.73
4   LP600005    L001   2025-06-01       139608.28       65218.76

   total_payment payment_status payment_month  payment_year
0      204827.04           Paid       2025-02          2025
1      204827.04           Paid       2025-03          2025
2      204827.04           Paid       2025-04          2025
3      204827.04           Paid       2025-05          2025
4      204827.04           Paid       2025-06          2025

In [75]:
# ==========================================
# BANK TRANSACTIONS - DATA TRANSFORMATION
# ==========================================

# Convert transaction date
bank_transactions_df["transaction_date"] = pd.to_datetime(
    bank_transactions_df["transaction_date"],
    errors="coerce"
)

# Clean transaction type
bank_transactions_df["transaction_type"] = (
    bank_transactions_df["transaction_type"]
    .astype(str)
    .str.strip()
    .str.title()
)

# Clean reference ID
bank_transactions_df["reference_id"] = (
    bank_transactions_df["reference_id"]
    .astype(str)
    .str.strip()
)

# Convert amount to numeric
bank_transactions_df["amount"] = pd.to_numeric(
    bank_transactions_df["amount"],
    errors="coerce"
)

# Transaction month
bank_transactions_df["transaction_month"] = (
    bank_transactions_df["transaction_date"]
    .dt.to_period("M")
    .astype(str)
)

# Transaction year
bank_transactions_df["transaction_year"] = (
    bank_transactions_df["transaction_date"]
    .dt.year
)

print("Bank Transactions transformations completed successfully!")

print(
    bank_transactions_df[
        [
            "bank_txn_id",
            "transaction_date",
            "transaction_type",
            "reference_id",
            "amount",
            "transaction_month",
            "transaction_year"
        ]
    ].head()
)

Bank Transactions transformations completed successfully!
  bank_txn_id transaction_date  transaction_type reference_id       amount  \
0    BT700000       2025-01-01   Opening Capital      CAPITAL  12000000.00
1    BT700462       2025-01-18  Customer Receipt     SI100515      2865.19
2    BT704822       2025-01-22    Vendor Payment     VI200356     -7692.25
3    BT705495       2025-01-22    Vendor Payment     VI201114     -4384.09
4    BT702903       2025-01-23  Customer Receipt     SI103229      3628.27

  transaction_month  transaction_year
0           2025-01              2025
1           2025-01              2025
2           2025-01              2025
3           2025-01              2025
4           2025-01              2025

In [76]:
# ==========================================
# INVENTORY SNAPSHOTS - DATA TRANSFORMATION
# ==========================================

# Convert snapshot date
inventory_snapshots_df["snapshot_date"] = pd.to_datetime(
    inventory_snapshots_df["snapshot_date"],
    errors="coerce"
)

# Convert numeric columns
inventory_snapshots_df["units_on_hand"] = pd.to_numeric(
    inventory_snapshots_df["units_on_hand"],
    errors="coerce"
)

inventory_snapshots_df["inventory_value"] = pd.to_numeric(
    inventory_snapshots_df["inventory_value"],
    errors="coerce"
)

# Snapshot month
inventory_snapshots_df["snapshot_month"] = (
    inventory_snapshots_df["snapshot_date"]
    .dt.to_period("M")
    .astype(str)
)

# Snapshot year
inventory_snapshots_df["snapshot_year"] = (
    inventory_snapshots_df["snapshot_date"]
    .dt.year
)

print("Inventory Snapshots transformations completed successfully!")

print(
    inventory_snapshots_df[
        [
            "inventory_snapshot_id",
            "snapshot_date",
            "product_id",
            "units_on_hand",
            "inventory_value",
            "snapshot_month",
            "snapshot_year"
        ]
    ].head()
)

Inventory Snapshots transformations completed successfully!
  inventory_snapshot_id snapshot_date product_id  units_on_hand  \
0             INV800001    2025-01-01      P3001             71
1             INV800002    2025-01-01      P3002             84
2             INV800003    2025-01-01      P3003             86
3             INV800004    2025-01-01      P3004             59
4             INV800005    2025-01-01      P3005             84

   inventory_value snapshot_month  snapshot_year
0         80651.03        2025-01           2025
1        169772.40        2025-01           2025
2        210400.72        2025-01           2025
3         84106.27        2025-01           2025
4         72315.60        2025-01           2025

In [77]:
# ==========================================
# FINAL DATASET SUMMARY
# ==========================================

datasets = {
    "Customers": customers_df,
    "Vendors": vendors_df,
    "Products": products_df,
    "Sales Invoices": sales_invoices_df,
    "Vendor Invoices": vendor_invoices_df,
    "Operating Expenses": operating_expenses_df,
    "Payroll": payroll_df,
    "Loans": loans_df,
    "Loan Payments": loan_payments_df,
    "Bank Transactions": bank_transactions_df,
    "Inventory Snapshots": inventory_snapshots_df
}

print("=" * 60)
print("FINAL DATASET SUMMARY")
print("=" * 60)

for name, df in datasets.items():
    print(f"{name:25} : {len(df):>6} rows | {len(df.columns):>2} columns")

============================================================
FINAL DATASET SUMMARY
============================================================
Customers                 :    120 rows |  5 columns
Vendors                   :     45 rows |  4 columns
Products                  :     60 rows |  5 columns
Sales Invoices            :   5000 rows | 17 columns
Vendor Invoices           :   2200 rows | 12 columns
Operating Expenses        :    160 rows |  6 columns
Payroll                   :     20 rows |  7 columns
Loans                     :      3 rows |  8 columns
Loan Payments             :     41 rows |  9 columns
Bank Transactions         :   6700 rows |  7 columns
Inventory Snapshots       :   1200 rows |  7 columns

In [78]:
# ==========================================
# FINAL DATA QUALITY VALIDATION
# ==========================================

key_columns = {
    "Customers": "customer_id",
    "Vendors": "vendor_id",
    "Products": "product_id",
    "Sales Invoices": "invoice_id",
    "Vendor Invoices": "vendor_invoice_id",
    "Operating Expenses": "expense_id",
    "Payroll": "payroll_id",
    "Loans": "loan_id",
    "Loan Payments": "payment_id",
    "Bank Transactions": "bank_txn_id",
    "Inventory Snapshots": "inventory_snapshot_id"
}

print("=" * 70)
print("FINAL DATA QUALITY VALIDATION")
print("=" * 70)

for name, df in datasets.items():

    key = key_columns[name]

    duplicate_count = df[key].duplicated().sum()
    missing_count = df.isnull().sum().sum()

    print(f"\n{name}")
    print("-" * 50)
    print(f"Rows              : {len(df)}")
    print(f"Columns           : {len(df.columns)}")
    print(f"Duplicate {key:<18}: {duplicate_count}")
    print(f"Total missing     : {missing_count}")

print("\n" + "=" * 70)
print("DATA TYPES")
print("=" * 70)

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

======================================================================
FINAL DATA QUALITY VALIDATION
======================================================================

Customers
--------------------------------------------------
Rows              : 120
Columns           : 5
Duplicate customer_id       : 0
Total missing     : 0

Vendors
--------------------------------------------------
Rows              : 45
Columns           : 4
Duplicate vendor_id         : 0
Total missing     : 0

Products
--------------------------------------------------
Rows              : 60
Columns           : 5
Duplicate product_id        : 0
Total missing     : 0

Sales Invoices
--------------------------------------------------
Rows              : 5000
Columns           : 17
Duplicate invoice_id        : 0
Total missing     : 1988

Vendor Invoices
--------------------------------------------------
Rows              : 2200
Columns           : 12
Duplicate vendor_invoice_id : 0
Total missing     : 900

Operating Expenses
--------------------------------------------------
Rows              : 160
Columns           : 6
Duplicate expense_id        : 0
Total missing     : 0

Payroll
--------------------------------------------------
Rows              : 20
Columns           : 7
Duplicate payroll_id        : 0
Total missing     : 0

Loans
--------------------------------------------------
Rows              : 3
Columns           : 8
Duplicate loan_id           : 0
Total missing     : 0

Loan Payments
--------------------------------------------------
Rows              : 41
Columns           : 9
Duplicate payment_id        : 0
Total missing     : 0

Bank Transactions
--------------------------------------------------
Rows              : 6700
Columns           : 7
Duplicate bank_txn_id       : 0
Total missing     : 0

Inventory Snapshots
--------------------------------------------------
Rows              : 1200
Columns           : 7
Duplicate inventory_snapshot_id: 0
Total missing     : 0

======================================================================
DATA TYPES
======================================================================

Customers
customer_id          object
customer_name        object
customer_segment     object
region               object
credit_terms_days     int64
dtype: object

Vendors
vendor_id             object
vendor_name           object
vendor_category       object
payment_terms_days     int64
dtype: object

Products
product_id        object
product_name      object
category          object
unit_cost        float64
selling_price    float64
dtype: object

Sales Invoices
invoice_id                    object
invoice_date          datetime64[ns]
customer_id                   object
product_id                    object
quantity                       int64
discount_pct                 float64
unit_price                   float64
gross_amount                 float64
discount_amount              float64
net_invoice_amount           float64
due_date              datetime64[ns]
payment_date          datetime64[ns]
payment_status                object
days_to_pay                  float64
days_late                    float64
invoice_month                 object
ageing_bucket               category
dtype: object

Vendor Invoices
vendor_invoice_id            object
invoice_date         datetime64[ns]
vendor_id                    object
expense_category             object
invoice_amount              float64
due_date             datetime64[ns]
payment_date         datetime64[ns]
payment_status               object
days_to_pay                 float64
days_late                   float64
invoice_month                object
ageing_bucket              category
dtype: object

Operating Expenses
expense_id                  object
expense_date        datetime64[ns]
expense_category            object
amount                     float64
expense_month               object
expense_year                 int32
dtype: object

Payroll
payroll_id                    object
pay_date              datetime64[ns]
gross_payroll                float64
tax_and_deductions           float64
net_payroll                  float64
pay_month                     object
pay_year                       int32
dtype: object

Loans
loan_id                         object
loan_type                       object
principal_amount                 int64
annual_interest_rate           float64
start_date              datetime64[ns]
tenure_months                    int64
loan_month                      object
loan_year                        int32
dtype: object

Loan Payments
payment_id                object
loan_id                   object
payment_date      datetime64[ns]
principal_paid           float64
interest_paid            float64
total_payment            float64
payment_month             object
payment_year               int32
payment_status            object
dtype: object

Bank Transactions
bank_txn_id                  object
transaction_date     datetime64[ns]
transaction_type             object
reference_id                 object
amount                      float64
transaction_month            object
transaction_year              int32
dtype: object

Inventory Snapshots
inventory_snapshot_id            object
snapshot_date            datetime64[ns]
product_id                       object
units_on_hand                     int64
inventory_value                 float64
snapshot_month                   object
snapshot_year                     int32
dtype: object